### ISSUE TITLE
Applying multiple jsonnet-reformat-buffer adds odd newlines at the end of the file.

### ISSUE THREAD

**Issue by Andor** [tminor/jsonnet-mode#21] opened 2020-10-08 21:36 UTC
When I press `C-c C-r` my buffers appears reformatted but the mode adds some odd newlines at the end of file.
If I will apply reformat multiple times it will add up to 4 newlines and only after that message `No format change necessary.` will appear.

UPD: apparently it works only if file ends with comment line like this:
<img width="212" alt="Screenshot 2020-10-09 at 0 37 53" src="https://user-images.githubusercontent.com/147300/95516272-acf7e080-09c7-11eb-9146-34e9565a767f.png">

**Comment by seh** [comment] 2020-10-08 21:42
That's new behavior. I've been using my patch from seh/jsonnet-mode@1b6eb2ef191fba7358412f1ef0d94c22a309b0f7 for over a year (despite the apparent commit date as seen in GitHub), and I haven't noticed this problem.

**Comment by Andor** [comment] 2020-10-08 21:48
@seh are you sure you tried to reproduce with comment at the end of the file?

**Comment by seh** [comment] 2020-10-08 23:23
Ah, I apologize. That problem _does_ arise in my version.

It's a problem with _jsonnetfmt_. I can reproduce it via `shell-command-on-region`. Use <kbd>C-x h</kbd> to select the entire buffer, then <kbd>C-u M-x shell-command-on-region RET</kbd>, and observe how the buffer grows by one line.

**Comment by Andor** [comment] 2020-10-08 23:39
I guess the issue is here: https://github.com/google/jsonnet/blob/520961df765b1744b1576bfda00c68311b826d87/core/libjsonnet.cpp#L440

**Comment by Andor** [comment] 2020-10-08 23:43
And at the same time go-jsonnet has this comment:
```
Final whitespace is stripped at lexing time.  Add a single new line as files ought to end with a new line.
```
https://github.com/google/go-jsonnet/blob/b70cbd441a39d7e1d6f3cf5e0f54be86357c6e04/internal/formatter/jsonnetfmt.go#L181

**Comment by Andor** [comment] 2020-10-08 23:48
Here is the main project issue report: https://github.com/google/jsonnet/issues/849

**Comment by tminor** [comment] 2021-12-28 13:26
This seems to be fixed with the [latest release](https://github.com/google/jsonnet/releases/tag/v0.18.0). Closing.

**Closed by tminor** 2021-12-28 13:26 UTC
