### ISSUE TITLE
Broken highlighting on stdlib-content.jsonnet

### ISSUE THREAD

**Issue by Andor** [tminor/jsonnet-mode#19] opened 2020-10-02 10:20 UTC
I have problems with highlighting when I am trying to open file https://github.com/google/jsonnet/blob/master/doc/_stdlib_gen/stdlib-content.jsonnet
Here is the stuff:
![image](https://user-images.githubusercontent.com/147300/94913439-f28d4880-04b1-11eb-9b76-bbb73cadefcc.png)

**Comment by tminor** [comment] 2020-10-02 13:59
I've noticed quite a few inconsistencies with syntax highlighting as well. I'm hesitant to try too hard with the current syntax highlighting implementation as it feels very similar to the current problems with `jsonnet-calculate-indent`: regex-based syntax parsing is too error-prone.

I'm curious about [emacs-tree-sitter](https://github.com/ubolonton/emacs-tree-sitter) as a solution to this problem. It would require a lot of up front work but would (theoretically) improve performance and debuggability. I very briefly started working on a `tree-sitter` parser for Jsonnet, but it's very far from working. I started by using [tree-sitter-json](https://github.com/tree-sitter/tree-sitter-json) as a base and the grammar currently covers a tiny amount of [the Jsonnet specification](https://jsonnet.org/ref/spec.html).

**Comment by Andor** [comment] 2020-10-02 16:44
@tminor yeah for sure full-featured language parser would be cool, but for most cases a simpler solution should be OK as well. Maybe you can find an easy fix for this issue without re-writing everything?
If you have clues please tell and I will try to fix it myself.

**Comment by tminor** [comment] 2020-10-02 17:24
You're right! I haven't examined this mode's syntax highlighting functions very closely, so the best I can do (for now, at least) is point you to [`jsonnet--font-lock-open-multiline-string`](https://github.com/tminor/jsonnet-mode/blob/master/jsonnet-mode.el#L344-L357) and [`jsonnet--font-lock-close-multiline-string`](https://github.com/tminor/jsonnet-mode/blob/master/jsonnet-mode.el#L390-L400).

I recall making some slight changes in [`jsonnet--syntax-propertize-function`](https://github.com/tminor/jsonnet-mode/blob/master/jsonnet-mode.el#L390-L400) in an attempt to fix that behavior but it clearly needs more work!

**Comment by tminor** [comment] 2020-10-02 17:28
Hmmm... maybe the aforementioned fix handles the case you referenced:

![Selection_058](https://user-images.githubusercontent.com/11579850/94951911-18671d00-04b3-11eb-9ef7-636038669d11.png)

**Comment by tminor** [comment] 2020-10-02 17:29
@Andor Could you try the most recent release and let me know if you still see the same inconsistency?

**Comment by Andor** [comment] 2020-10-02 18:09
@tminor I use latest release `20200930.1418`. Tried to re-install because I played with it a bit, but yields the same.

**Comment by tminor** [comment] 2020-10-03 17:16
I was also able to reproduce this with `emacs -Q` on `"GNU Emacs 26.3 (build 1, x86_64-redhat-linux-gnu, GTK+ Version 3.24.13)
 of 2019-12-10"`. I'm not sure yet how to debug this, but I was able to coerce proper syntax highlighting by adding a space before the opening `|||`. I tried to reproduce this as minimally as possible (with a smaller bit of Jsonnet code) but wasn't successful.

**Comment by tminor** [comment] 2020-10-04 00:36
@Andor This appears to be an issue with `jit-lock-mode` and [multiline pattern matching](https://www.gnu.org/software/emacs/manual/html_node/elisp/Multiline-Font-Lock.html). I've experimented a bit with setting the `font-lock-multiline` property on multiline strings which seems to fix all but one instance of incorrectly fontified multiline strings in that file.

**Comment by tminor** [comment] 2021-03-02 15:59
I promise I haven't forgotten about this. I looked at this for a few hours a week or two ago with tools like [`font-lock-studio`](https://github.com/Lindydancer/font-lock-studio) but I didn't get any closer to finding the root cause. My last comment mentioned multiline pattern matching and its section in the Elisp manual; here's a quote from that section:

> Making elements that match multiline constructs work properly has two aspects: correct identification and correct rehighlighting. The first means that Font Lock finds all multiline constructs. The second means that Font Lock will correctly rehighlight all the relevant text when a multiline construct is changed—for example, if some of the text that was previously part of a multiline construct ceases to be part of it. The two aspects are closely related, and often getting one of them to work will appear to make the other also work. However, for reliable results you must attend explicitly to both aspects.

I think this problem fails for the first aspect mentioned above. Running `font-lock-studio`, it looks like some fontification/highlighting happens before Font Lock keywords are applied. Here's a screenshot:

![jsonnet-font-lock-studio](https://user-images.githubusercontent.com/11579850/109675939-3ad69280-7b46-11eb-8a7c-9d8e51100801.png)

I almost certainly need to spend more time reading Font Lock's documentation before understanding how to fix this.

**Comment by Andor** [comment] 2021-03-02 18:21
@tminor I believe in you dude!

**Comment by anguslees** [comment] 2021-03-12 05:48
Probably related bug report (otherwise I'm happy to open a new issue):  `/*` inside a `|||` block breaks indenting of following lines.

```jsonnet
|||
  this line is a quoted string, but also contains: /*
  bug: press <tab> on this line and see where it gets indented.
|||;
```

I had a fix for this earlier: https://github.com/tminor/jsonnet-mode/issues/9#issuecomment-469940396 but I haven't retried this patch with the smie changes.

(I'm using `;; Package-Commit: e93a1f55e5f9bc2b34b025c6f7a60a6f159268d1`)

**Comment by tminor** [comment] 2021-03-12 15:09
I've been meaning to set `jsonnet-use-smie` to `t` by default but it's still a little inconsistent for relatively common indentation cases (but I still think it's better than the default indent function). Maybe soon? Who knows!

**Comment by tminor** [comment] 2021-03-15 16:24
My comment from 2 weeks ago was posted while shaving the wrong yak, it seems. From `font-lock-studio`'s README:

> When Font Lock Studio is started, comments and strings are pre-colored, as they are part of the earlier syntactic phase (which isn't supported by Font Lock Studio).

So... maybe it's somewhere in [this region](https://github.com/tminor/jsonnet-mode/blob/master/jsonnet-mode.el#L414-L446)?

**Closed** 2022-01-21 21:13 UTC
